// This file is auto-generated by: npm run db:generate
// For now, manual types — run the generate command after connecting to Supabase.

export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id:                      string
          email:                   string | null
          full_name:               string | null
          avatar_url:              string | null
          plan:                    'free' | 'starter' | 'pro'
          stripe_customer_id:      string | null
          stripe_subscription_id:  string | null
          subscription_status:     string | null
          subscription_ends_at:    string | null
          created_at:              string
          updated_at:              string
        }
        Insert: {
          id:                      string
          email?:                  string | null
          full_name?:              string | null
          avatar_url?:             string | null
          plan?:                   'free' | 'starter' | 'pro'
          stripe_customer_id?:     string | null
          stripe_subscription_id?: string | null
          subscription_status?:    string | null
          subscription_ends_at?:   string | null
          created_at?:             string
          updated_at?:             string
        }
        Update: {
          id?:                     string
          email?:                  string | null
          full_name?:              string | null
          avatar_url?:             string | null
          plan?:                   'free' | 'starter' | 'pro'
          stripe_customer_id?:     string | null
          stripe_subscription_id?: string | null
          subscription_status?:    string | null
          subscription_ends_at?:   string | null
          created_at?:             string
          updated_at?:             string
        }
      }
      sites: {
        Row: {
          id:            string
          user_id:       string
          name:          string
          type:          string
          html:          string | null
          deployed_url:  string | null
          custom_domain: string | null
          is_published:  boolean
          created_at:    string
          updated_at:    string
        }
        Insert: {
          id?:           string
          user_id:       string
          name:          string
          type:          string
          html?:         string | null
          deployed_url?: string | null
          custom_domain?: string | null
          is_published?: boolean
          created_at?:   string
          updated_at?:   string
        }
        Update: {
          id?:           string
          user_id?:      string
          name?:         string
          type?:         string
          html?:         string | null
          deployed_url?: string | null
          custom_domain?: string | null
          is_published?: boolean
          created_at?:   string
          updated_at?:   string
        }
      }
      messages: {
        Row: {
          id:         string
          site_id:    string
          user_id:    string
          role:       'user' | 'assistant'
          content:    string
          created_at: string
        }
        Insert: {
          id?:        string
          site_id:    string
          user_id:    string
          role:       'user' | 'assistant'
          content:    string
          created_at?: string
        }
        Update: {
          id?:        string
          site_id?:   string
          user_id?:   string
          role?:      'user' | 'assistant'
          content?:   string
          created_at?: string
        }
      }
      versions: {
        Row: {
          id:         string
          site_id:    string
          user_id:    string
          html:       string
          note:       string | null
          created_at: string
        }
        Insert: {
          id?:        string
          site_id:    string
          user_id:    string
          html:       string
          note?:      string | null
          created_at?: string
        }
        Update: {
          id?:        string
          site_id?:   string
          user_id?:   string
          html?:      string
          note?:      string | null
          created_at?: string
        }
      }
      contact_submissions: {
        Row: {
          id:         string
          site_id:    string
          form_name:  string
          data:       Record<string, string> | null
          ip:         string | null
          read_at:    string | null
          // legacy fixed columns
          name:       string | null
          email:      string | null
          message:    string | null
          read:       boolean | null
          created_at: string
        }
        Insert: {
          id?:        string
          site_id:    string
          form_name?: string
          data?:      Record<string, string> | null
          ip?:        string | null
          read_at?:   string | null
          name?:      string | null
          email?:     string | null
          message?:   string | null
          created_at?: string
        }
        Update: {
          read_at?: string | null
          read?:    boolean | null
        }
      }
    }
    Views: {
      user_limits: {
        Row: {
          id:                    string
          plan:                  string
          site_count:            number
          max_sites:             number
          can_use_custom_domain: boolean
        }
        Relationships: []
      }
    }
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

// Convenience types
export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
